name: ImmersiveElevators
version: '${project.version}'
main: top.azimkin.ImmersiveElevators
api-version: '1.16'
load: STARTUP

commands:
  createlift:
    usage: /createlift <Name> <buttonX> <Y> <Z> <levels>
    permission: ie.create
    aliases: cl
  addfloor:
    usage: /addfloor <lift name> <floor> <Y>
    permission: ie.addfloor
  imeersiveelevators:
    usage: /el
    permission: ie.admin
    aliases: el
