name: ImmersiveElevators
version: '${project.version}'
main: top.azimkin.ImmersiveElevators
api-version: '1.16'
load: POSTWORLD

commands:
  elevators:
    usage: /el help
    permission: ie.commands.el
    description: main command
    aliases:
      - ie
      - el
      - immersiveelevators